// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoiuzbsipcmorxbjnhmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvaXV6YnNpcGNtb3J4YmpuaG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTIwMTksImV4cCI6MjA2MjE4ODAxOX0.bvvJQKpTKoaB11flkB7Q90m-pfU2uaWqLcvkfsu_1hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);